begin;

select plan(82);

select has_table('public','conduct_events','conduct events exist');
select has_table('public','learner_support_cases','learner support cases exist');
select has_table('public','learning_resource_copies','learning resource copies exist');
select has_table('public','communication_messages','communication messages exist');
select has_table('public','communication_delivery_jobs','communication delivery outbox exists');
select has_table('public','communication_provider_routes','communication provider routes exist');
select has_table('public','communication_delivery_attempts','communication delivery attempt history exists');
select has_table('public','admission_applications','admission applications exist');
select has_table('public','transfer_events','transfer events exist');
select has_table('public','year_end_progressions','year-end progressions exist');
select has_table('public','examination_candidates','examination candidates exist');
select has_table('public','examination_readiness_issues','examination readiness issues exist');
select has_table('public','finance_invoices','finance invoices exist');
select has_table('public','finance_payments','finance payments exist');
select has_table('public','tenant_features','tenant features exist');
select has_table('public','school_settings','school settings exist');
select has_table('public','guardian_profiles','guardian profiles exist');
select has_table('public','learner_guardians','learner guardian relationships exist');
select has_table('public','guardian_contacts','guardian contacts exist');
select has_table('public','guardian_user_links','guardian user links exist');
select has_table('public','import_batches','import batches exist');
select has_table('public','import_rows','import staging rows exist');
select has_table('public','subject_attendance_submissions','subject attendance submissions exist');
select has_table('public','school_late_arrival_events','school late arrival events exist');
select has_table('public','late_detention_obligations','late detention obligations exist');
select has_table('public','detention_sessions','detention sessions exist');
select has_table('public','detention_session_items','detention session items exist');
select has_table('public','report_card_documents','report card documents exist');
select has_table('public','report_card_render_jobs','report card render outbox exists');

select ok((select relrowsecurity from pg_class where oid='public.learner_support_cases'::regclass),'learner support cases use RLS');
select ok((select relrowsecurity from pg_class where oid='public.examination_candidates'::regclass),'examination candidates use RLS');
select ok((select relrowsecurity from pg_class where oid='public.finance_payments'::regclass),'finance payments use RLS');
select ok((select relrowsecurity from pg_class where oid='public.tenant_features'::regclass),'tenant features use RLS');
select ok((select relrowsecurity from pg_class where oid='public.guardian_profiles'::regclass),'guardian profiles use RLS');
select ok((select relrowsecurity from pg_class where oid='public.import_batches'::regclass),'import batches use RLS');
select ok((select relrowsecurity from pg_class where oid='public.subject_attendance_submissions'::regclass),'subject attendance submissions use RLS');
select ok((select relrowsecurity from pg_class where oid='public.communication_delivery_jobs'::regclass),'communication delivery jobs use RLS');
select ok((select relrowsecurity from pg_class where oid='public.communication_provider_routes'::regclass),'communication provider routes use RLS');
select ok((select relrowsecurity from pg_class where oid='public.communication_delivery_attempts'::regclass),'communication delivery attempts use RLS');
select ok((select relrowsecurity from pg_class where oid='public.detention_sessions'::regclass),'detention sessions use RLS');
select ok((select relrowsecurity from pg_class where oid='public.detention_session_items'::regclass),'detention session items use RLS');
select ok((select relrowsecurity from pg_class where oid='public.report_card_documents'::regclass),'report card documents use RLS');
select ok((select relrowsecurity from pg_class where oid='public.report_card_render_jobs'::regclass),'report card render jobs use RLS');

select ok(to_regprocedure('public.refresh_examination_readiness(uuid)') is not null,'DNEA readiness refresh function exists');
select ok(not has_function_privilege('anon','public.refresh_examination_readiness(uuid)','EXECUTE'),'anonymous users cannot refresh DNEA readiness');
select ok(to_regprocedure('public.allocate_finance_payment(uuid,uuid,numeric)') is not null,'finance payment allocation function exists');
select ok(not has_function_privilege('anon','public.allocate_finance_payment(uuid,uuid,numeric)','EXECUTE'),'anonymous users cannot allocate payments');
select ok(to_regprocedure('public.set_tenant_feature(uuid,text,boolean,jsonb,date)') is not null,'tenant feature function exists');
select ok(not has_function_privilege('anon','public.set_tenant_feature(uuid,text,boolean,jsonb,date)','EXECUTE'),'anonymous users cannot change tenant features');
select ok(to_regprocedure('public.set_school_setting(uuid,text,jsonb)') is not null,'school setting function exists');
select ok(to_regprocedure('public.upsert_guardian_relationship(uuid,uuid,text,text,text,text,text,boolean,boolean,boolean,smallint,jsonb)') is not null,'guardian relationship upsert function exists');
select ok(not has_function_privilege('anon','public.upsert_guardian_relationship(uuid,uuid,text,text,text,text,text,boolean,boolean,boolean,smallint,jsonb)','EXECUTE'),'anonymous users cannot manage guardian relationships');
select ok(to_regprocedure('public.link_existing_guardian_to_learner(uuid,uuid,text,boolean,boolean,boolean,smallint)') is not null,'existing guardian sibling-link function exists');
select ok(not has_function_privilege('anon','public.link_existing_guardian_to_learner(uuid,uuid,text,boolean,boolean,boolean,smallint)','EXECUTE'),'anonymous users cannot link existing guardians');
select ok(to_regprocedure('public.claim_guardian_profile(uuid)') is not null,'guardian account claim function exists');
select ok(not has_function_privilege('anon','public.claim_guardian_profile(uuid)','EXECUTE'),'anonymous users cannot claim guardian profiles');
select ok(to_regprocedure('public.create_import_batch(uuid,text,text,text)') is not null,'import batch creation function exists');
select ok(not has_function_privilege('anon','public.create_import_batch(uuid,text,text,text)','EXECUTE'),'anonymous users cannot create import batches');
select ok(to_regprocedure('public.reconcile_learner_import_batch(uuid)') is not null,'deterministic learner import reconciliation exists');
select ok(not has_function_privilege('anon','public.reconcile_learner_import_batch(uuid)','EXECUTE'),'anonymous users cannot reconcile learner imports');
select ok(to_regprocedure('public.commit_learner_import_batch(uuid)') is not null,'atomic learner import commit function exists');
select ok(not has_function_privilege('anon','public.commit_learner_import_batch(uuid)','EXECUTE'),'anonymous users cannot commit learner imports');
select ok(to_regprocedure('public.claim_communication_delivery_jobs(integer)') is not null,'communication delivery claim function exists');
select ok(not has_function_privilege('authenticated','public.claim_communication_delivery_jobs(integer)','EXECUTE'),'authenticated clients cannot claim provider delivery jobs');
select ok(has_function_privilege('service_role','public.claim_communication_delivery_jobs(integer)','EXECUTE'),'service role can claim provider delivery jobs');
select ok(to_regprocedure('public.set_communication_provider_route(uuid,uuid,text,text,smallint,boolean,date,date,jsonb)') is not null,'communication provider route configuration function exists');
select ok(not has_function_privilege('anon','public.set_communication_provider_route(uuid,uuid,text,text,smallint,boolean,date,date,jsonb)','EXECUTE'),'anonymous users cannot configure communication provider routes');
select ok(to_regprocedure('public.resolve_communication_provider_route(uuid,uuid,text,date)') is not null,'service worker provider route resolver exists');
select ok(not has_function_privilege('authenticated','public.resolve_communication_provider_route(uuid,uuid,text,date)','EXECUTE'),'authenticated clients cannot resolve worker provider routes directly');
select ok(to_regprocedure('public.submit_subject_period_attendance(uuid,date,jsonb,text,uuid,uuid,text)') is not null,'subject-period attendance submission function exists');
select ok(not has_function_privilege('anon','public.submit_subject_period_attendance(uuid,date,jsonb,text,uuid,uuid,text)','EXECUTE'),'anonymous users cannot submit subject-period attendance');
select ok(to_regprocedure('public.assign_school_duty(uuid,uuid,text,date,date)') is not null,'school duty assignment function exists');
select ok(not has_function_privilege('anon','public.assign_school_duty(uuid,uuid,text,date,date)','EXECUTE'),'anonymous users cannot assign school duties');
select ok(to_regprocedure('public.create_detention_session(uuid,date,time,time,uuid,text,text)') is not null,'detention session creation function exists');
select ok(not has_function_privilege('anon','public.create_detention_session(uuid,date,time,time,uuid,text,text)','EXECUTE'),'anonymous users cannot create detention sessions');
select ok(to_regprocedure('public.populate_detention_session(uuid)') is not null,'detention session population function exists');
select ok(to_regprocedure('public.record_detention_attendance(uuid,uuid,text,text)') is not null,'detention attendance function exists');
select ok(not has_function_privilege('anon','public.record_detention_attendance(uuid,uuid,text,text)','EXECUTE'),'anonymous users cannot record detention attendance');
select ok(to_regprocedure('public.complete_detention_session(uuid,text)') is not null,'detention session completion function exists');
select ok(to_regprocedure('public.register_report_card_document(uuid,text,text,text,text,text,text,integer)') is not null,'report card document registration function exists');
select ok(not has_function_privilege('anon','public.register_report_card_document(uuid,text,text,text,text,text,text,integer)','EXECUTE'),'anonymous users cannot register report-card documents');
select ok(to_regprocedure('public.queue_report_card_render(uuid,text,text,text)') is not null,'report card render queue function exists');
select ok(not has_function_privilege('anon','public.queue_report_card_render(uuid,text,text,text)','EXECUTE'),'anonymous users cannot queue report-card renders');
select ok(to_regprocedure('public.claim_report_card_render_jobs(integer)') is not null,'report card render claim function exists');
select ok(not has_function_privilege('authenticated','public.claim_report_card_render_jobs(integer)','EXECUTE'),'authenticated clients cannot claim render jobs');
select ok(has_function_privilege('service_role','public.claim_report_card_render_jobs(integer)','EXECUTE'),'service role can claim render jobs');

select * from finish();
rollback;