begin;
select plan(14);
select has_function('public','reserve_staff_credential_issuance',array['uuid','uuid','uuid'],'reservation function exists');
select ok(not has_function_privilege('authenticated','public.reserve_staff_credential_issuance(uuid,uuid,uuid)','EXECUTE'),'authenticated cannot reserve');
select ok(not has_function_privilege('anon','public.reserve_staff_credential_issuance(uuid,uuid,uuid)','EXECUTE'),'anonymous cannot reserve');
select ok(has_function_privilege('service_role','public.reserve_staff_credential_issuance(uuid,uuid,uuid)','EXECUTE'),'service role can reserve');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%pg_advisory_xact_lock%','reservation serializes concurrent attempts');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%rate limit exceeded%','reservation enforces rate limits');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%staff account must be linked%','reservation refuses unlinked staff identities');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%cannot issue temporary credentials to themselves%','reservation prevents self issuance');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%protected administrator credentials%','reservation protects active school administrators');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%already in progress for this staff account%','reservation blocks concurrent live issuance for one staff account');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%platform_memberships%','reservation protects platform-level privileged accounts');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%education_network_memberships%','reservation protects education-network privileged accounts');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%Cross-school accounts cannot use managed school credentials%','reservation rejects account-global password takeover across schools');
select ok((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reserve_staff_credential_issuance') ilike '%guardian_user_links%','reservation protects guardian-linked identities');
select * from finish();
rollback;
