"use client";
import Link from "next/link";
import {useActionState,useEffect,useMemo,useState} from "react";
import {FileText,Search,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {Picker} from "@/components/ui/picker";
import {Spinner} from "@/components/ui/spinner";
import {reviewAbsenceNotice,type AbsenceReviewState} from "@/features/attendance/server/absence-actions";
import type {SchoolAbsenceNotice} from "@/features/attendance/server/absence-notices";
const initialState:AbsenceReviewState={};
function ReviewForm({notice}:{notice:SchoolAbsenceNotice}){const[state,action,pending]=useActionState(reviewAbsenceNotice,initialState);const[status,setStatus]=useState(notice.status==="submitted"?"under_review":notice.status);useEffect(()=>{if(!state.message)return;state.success?toast.success(state.message):toast.error(state.message);},[state]);return <form action={action} className="mt-3 grid gap-2 sm:grid-cols-[12rem_minmax(12rem,1fr)_auto] sm:items-end"><input type="hidden" name="noticeId" value={notice.id}/><Picker label="Review decision" name="status" value={status} onChange={setStatus} options={[{value:"under_review",label:"Under review"},{value:"accepted",label:"Accepted"},{value:"returned",label:"Needs clarification"},{value:"closed",label:"Closed"}]}/><label className="text-xs font-medium">School note<input name="note" defaultValue={notice.reviewNote??""} className="mt-1.5 min-h-10 w-full rounded-[var(--radius-sm)] border border-border-subtle bg-surface-elevated px-3 text-sm outline-none focus:ring-4 focus:ring-[color:var(--brand-soft)]"/></label><button disabled={pending} className="inline-flex min-h-10 items-center justify-center gap-1.5 rounded-[var(--radius-sm)] bg-brand px-3 text-xs font-semibold text-white disabled:opacity-60">{pending?<Spinner className="size-3.5 text-white"/>:<ShieldCheck className="size-3.5"/>}{pending?"Saving…":"Save review"}</button></form>}
export function AbsenceNoticeReview({notices}:{notices:SchoolAbsenceNotice[]}){const[query,setQuery]=useState("");const[status,setStatus]=useState("open");const visible=useMemo(()=>notices.filter((item)=>{const matches=!query||`${item.learnerName} ${item.admissionNumber??""} ${item.className??""}`.toLowerCase().includes(query.toLowerCase());const matchesStatus=status==="all"||(status==="open"?["submitted","under_review","returned"].includes(item.status):item.status===status);return matches&&matchesStatus;}),[notices,query,status]);return <div className="space-y-4"><div className="grid gap-3 rounded-[var(--radius-md)] bg-surface-muted p-3 sm:grid-cols-[minmax(0,1fr)_14rem]"><label className="scolapro-control-surface flex min-h-10 items-center gap-2 rounded-[var(--radius-sm)] px-3"><Search className="size-4 text-muted-foreground"/><span className="sr-only">Search notices</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Learner, admission number or class…" className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><Picker label="" name="noticeStatusFilter" value={status} onChange={setStatus} options={[{value:"open",label:"Open review work"},{value:"submitted",label:"Submitted"},{value:"under_review",label:"Under review"},{value:"accepted",label:"Accepted"},{value:"returned",label:"Needs clarification"},{value:"closed",label:"Closed"},{value:"all",label:"All notices"}]}/></div>{visible.length?<div className="divide-y divide-border-subtle rounded-[var(--radius-md)] bg-surface px-4 shadow-[var(--shadow-xs)] sm:px-5">{visible.map((notice)=><article key={notice.id} className="py-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><Link href={`/learners/${notice.learnerId}`} className="scolapro-record-title hover:text-brand">{notice.learnerName}</Link><p className="mt-1 text-xs text-muted-foreground">{notice.className??"Class"} · {notice.admissionNumber??"No admission number"} · {notice.absenceFrom}{notice.absenceTo!==notice.absenceFrom?` – ${notice.absenceTo}`:""}</p><p className="mt-2 text-sm capitalize">{notice.reasonCategory.replaceAll("_"," ")}{notice.message?` · ${notice.message}`:""}</p></div><span className="self-start rounded-[var(--radius-xs)] bg-info-soft px-2 py-1 text-[0.65rem] font-semibold capitalize text-[color:var(--info)]">{notice.status.replaceAll("_"," ")}</span></div><div className="mt-2 flex flex-wrap gap-2">{notice.attachments.map((attachment)=><a key={attachment.id} href={`/api/absence-attachments/${attachment.id}`} target="_blank" className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand"><FileText className="size-3.5"/>{attachment.fileName}</a>)}</div><ReviewForm notice={notice}/></article>)}</div>:<div className="rounded-[var(--radius-md)] bg-surface px-4 py-10 text-center text-sm text-muted-foreground shadow-[var(--shadow-xs)]">No absence notices match these filters.</div>}</div>}
