"use client";

import { useActionState, useEffect, useState } from "react";
import { CalendarCheck2, FileText, Upload } from "lucide-react";
import { toast } from "sonner";
import { DateField } from "@/components/ui/date-field";
import { Picker } from "@/components/ui/picker";
import { Spinner } from "@/components/ui/spinner";
import { submitAbsenceNotice, type ParentPortalActionState } from "@/features/parents/server/actions";
import type { ParentAbsenceNotice, ParentChildSummary } from "@/features/parents/server/portal";

const initialState: ParentPortalActionState = {};
const reasons=["illness","medical_appointment","compassionate","family","transport","weather","school_activity","other"].map((value)=>({value,label:value.replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase())}));

export function ParentAbsenceNotices({ children, notices }: { children: ParentChildSummary[]; notices: ParentAbsenceNotice[] }) {
  const [state, action, pending]=useActionState(submitAbsenceNotice,initialState);
  const [learnerId,setLearnerId]=useState(children[0]?.learnerId??""); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [reason,setReason]=useState("illness");
  useEffect(()=>{if(!state.message)return; state.success?toast.success(state.message):toast.error(state.message);},[state]);
  return <section className="grid gap-5 lg:grid-cols-[minmax(18rem,0.75fr)_minmax(0,1.25fr)]">
    <form action={action} className="rounded-[var(--radius-md)] bg-surface p-4 shadow-[var(--shadow-xs)] sm:p-5"><div className="mb-4"><h2 className="scolapro-section-title">Submit absence evidence</h2><p className="scolapro-section-description">Send a private supporting document to the school. Submission does not automatically alter the official attendance register.</p></div><Picker label="Learner" name="learnerId" value={learnerId} onChange={setLearnerId} placeholder="Choose learner" options={children.map((child)=>({value:child.learnerId,label:child.name,helper:child.registerClass??undefined}))}/><div className="mt-3 grid gap-3 sm:grid-cols-2"><DateField label="Absent from" name="absenceFrom" value={from} onChange={setFrom} required/><DateField label="Absent to" name="absenceTo" value={to} onChange={setTo} min={from||undefined} required/></div><div className="mt-3"><Picker label="Reason" name="reason" value={reason} onChange={setReason} options={reasons}/></div><label className="mt-3 block text-xs font-medium">Short note<textarea name="message" maxLength={1000} rows={3} className="mt-1.5 w-full resize-none rounded-[var(--radius-sm)] border border-border-subtle bg-surface-elevated p-3 text-sm outline-none focus:ring-4 focus:ring-[color:var(--brand-soft)]"/></label><input id="absence-attachment" name="attachment" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="sr-only" required/><label htmlFor="absence-attachment" className="mt-3 flex min-h-20 cursor-pointer items-center justify-center gap-2 rounded-[var(--radius-sm)] border border-dashed border-border bg-surface-muted px-3 text-xs font-medium text-muted-foreground hover:bg-brand-soft/40"><Upload className="size-4 text-brand"/>Choose private document · max 10 MB</label><button disabled={pending||!learnerId||!from||!to} className="mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-[var(--radius-sm)] bg-brand px-4 text-sm font-semibold text-white disabled:opacity-60">{pending?<Spinner className="size-4 text-white"/>:<CalendarCheck2 className="size-4"/>}{pending?"Submitting…":"Submit for review"}</button></form>
    <div className="overflow-hidden rounded-[var(--radius-md)] bg-surface shadow-[var(--shadow-xs)]"><div className="border-b border-border-subtle px-4 py-4 sm:px-5"><h2 className="scolapro-section-title">Submitted notices</h2><p className="scolapro-section-description">Review status and school feedback remain visible here.</p></div>{notices.length?<div className="divide-y divide-border-subtle">{notices.map((notice)=><article key={notice.id} className="px-4 py-3 sm:px-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="scolapro-record-title">{notice.absenceFrom}{notice.absenceTo!==notice.absenceFrom?` – ${notice.absenceTo}`:""}</p><p className="mt-0.5 text-xs capitalize text-muted-foreground">{notice.reasonCategory.replaceAll("_"," ")}</p></div><span className="rounded-[var(--radius-xs)] bg-info-soft px-2 py-1 text-[0.65rem] font-semibold capitalize text-[color:var(--info)]">{notice.status.replaceAll("_"," ")}</span></div>{notice.reviewNote?<p className="mt-2 rounded-[var(--radius-xs)] bg-surface-muted px-3 py-2 text-xs text-muted-foreground">School note: {notice.reviewNote}</p>:null}<div className="mt-2 flex flex-wrap gap-2">{notice.attachments.map((attachment)=><a key={attachment.id} href={`/api/absence-attachments/${attachment.id}`} target="_blank" className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand"><FileText className="size-3.5"/>{attachment.fileName}</a>)}</div></article>)}</div>:<div className="px-4 py-10 text-center text-sm text-muted-foreground">No absence evidence submitted yet.</div>}</div>
  </section>;
}
