import { AlertTriangle, CheckCircle2, FileSpreadsheet, Upload } from "lucide-react";
import { redirect } from "next/navigation";
import { AppShell } from "@/components/shell/app-shell";
import { commitLearnerImport, markLearnerImportReady, stageLearnerCsv } from "@/features/imports/server/actions";
import { getImportWorkspace } from "@/features/imports/server/queries";
import { getUserContext } from "@/lib/auth/get-user-context";

export default async function SchoolImportsPage({ searchParams }: { searchParams: Promise<{ batch?: string; error?: string; success?: string }> }) {
  const context = await getUserContext();
  if (!context.user) redirect("/login");
  const membership = context.memberships[0];
  if (!membership || membership.roleKey !== "school_admin") redirect("/");
  const search = await searchParams;
  const workspace = await getImportWorkspace(membership.schoolId, search.batch);
  const batch = workspace.selectedBatch;

  return <AppShell><div className="space-y-5"><div><h1 className="scolapro-page-title text-xl">Bulk import</h1><p className="mt-1 text-sm text-muted-foreground">Stage learner CSV data, review reconciliation issues, then commit through the same governed learner-registration workflow used by ScolaPro.</p></div>
    {search.error?<div className="rounded-[var(--radius-sm)] bg-danger-soft p-3 text-xs font-medium text-[color:var(--danger)]">{search.error}</div>:null}{search.success?<div className="rounded-[var(--radius-sm)] bg-success-soft p-3 text-xs font-medium text-[color:var(--success)]">{search.success}</div>:null}
    <section className="grid gap-5 xl:grid-cols-[minmax(20rem,0.7fr)_minmax(0,1.3fr)]"><div className="bg-surface p-4 shadow-[var(--shadow-xs)] sm:p-5"><div className="flex items-start gap-3"><span className="scolapro-tone-mint grid size-9 shrink-0 place-items-center rounded-[var(--radius-sm)]"><Upload className="size-4"/></span><div><h2 className="scolapro-section-title">Stage learner CSV</h2><p className="scolapro-section-description">Required columns: first_names, surname, grade_code, class_code. Optional: preferred_name, date_of_birth, sex, admission_number, enrolled_from.</p></div></div><form action={stageLearnerCsv} className="mt-4"><input id="learner-csv" name="file" type="file" accept="text/csv,.csv" className="sr-only" required/><label htmlFor="learner-csv" className="flex min-h-28 cursor-pointer flex-col items-center justify-center gap-2 rounded-[var(--radius-sm)] border border-dashed border-border bg-surface-muted px-4 text-center hover:bg-brand-soft/40"><FileSpreadsheet className="size-6 text-brand"/><span className="text-xs font-semibold">Choose CSV file</span><span className="text-[0.68rem] text-muted-foreground">Maximum 2 MB. The file is staged before any learner record is created.</span></label><button type="submit" className="mt-3 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-[var(--radius-sm)] bg-brand px-4 text-sm font-semibold text-white">Stage and validate</button></form></div>
      <div className="bg-surface shadow-[var(--shadow-xs)]"><div className="border-b border-border-subtle px-4 py-4 sm:px-5"><h2 className="scolapro-section-title">Recent import batches</h2><p className="scolapro-section-description">Nothing enters the learner register until a ready batch is committed.</p></div>{workspace.batches.length?<div className="divide-y divide-border-subtle">{workspace.batches.map((item)=><a key={item.id} href={`/school/imports?batch=${item.id}`} className={`flex items-center justify-between gap-3 px-4 py-3 sm:px-5 ${batch?.id===item.id?"bg-brand-soft/45":"hover:bg-surface-muted"}`}><span className="min-w-0"><span className="scolapro-record-title block truncate">{item.source_file_name}</span><span className="text-[0.68rem] text-muted-foreground">{item.total_rows} rows · {item.valid_rows} ready · {item.error_rows} errors</span></span><span className="rounded-[var(--radius-xs)] bg-surface-muted px-2 py-1 text-[0.65rem] font-medium capitalize text-muted-foreground">{item.status}</span></a>)}</div>:<div className="p-8 text-center text-xs text-muted-foreground">No imports staged yet.</div>}</div></section>
    {batch?<section className="bg-surface shadow-[var(--shadow-xs)]"><div className="flex flex-col gap-3 border-b border-border-subtle px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h2 className="scolapro-section-title">Review · {batch.source_file_name}</h2><p className="scolapro-section-description">{batch.total_rows} rows · {batch.valid_rows} ready · {batch.warning_rows} warnings · {batch.error_rows} errors</p></div><div className="flex gap-2">{batch.status==="review"&&batch.error_rows===0?<form action={markLearnerImportReady}><input type="hidden" name="batchId" value={batch.id}/><button className="min-h-9 rounded-[var(--radius-sm)] bg-brand-soft px-3 text-xs font-semibold text-brand-strong">Mark ready</button></form>:null}{batch.status==="ready"?<form action={commitLearnerImport}><input type="hidden" name="batchId" value={batch.id}/><button className="min-h-9 rounded-[var(--radius-sm)] bg-brand px-3 text-xs font-semibold text-white">Commit learners</button></form>:null}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[48rem] border-collapse text-left text-xs"><thead className="bg-surface-muted text-muted-foreground"><tr><th className="px-4 py-2 font-medium">Row</th><th className="px-4 py-2 font-medium">Learner</th><th className="px-4 py-2 font-medium">Placement</th><th className="px-4 py-2 font-medium">Resolution</th><th className="px-4 py-2 font-medium">Issues</th></tr></thead><tbody className="divide-y divide-border-subtle">{workspace.rows.map((row)=>{const issues=row.issues??[];return <tr key={row.id}><td className="px-4 py-2.5 text-muted-foreground">{row.row_number}</td><td className="px-4 py-2.5"><span className="font-medium">{row.normalized_data.first_names} {row.normalized_data.surname}</span>{row.normalized_data.admission_number?<span className="mt-0.5 block text-[0.68rem] text-muted-foreground">{row.normalized_data.admission_number}</span>:null}</td><td className="px-4 py-2.5 text-muted-foreground">{row.source_data.grade_code||row.source_data.grade||"—"} · {row.source_data.class_code||row.source_data.register_class||row.source_data.class||"—"}</td><td className="px-4 py-2.5"><span className={`inline-flex items-center gap-1 rounded-[var(--radius-xs)] px-2 py-1 font-medium ${row.resolution==="create"?"bg-success-soft text-[color:var(--success)]":"bg-danger-soft text-[color:var(--danger)]"}`}>{row.resolution==="create"?<CheckCircle2 className="size-3"/>:<AlertTriangle className="size-3"/>}{row.resolution}</span></td><td className="px-4 py-2.5 text-[0.68rem] text-muted-foreground">{issues.length?issues.map((issue)=>issue.message).join(" · "):"Ready"}</td></tr>})}</tbody></table></div></section>:null}
  </div></AppShell>;
}
