"use client";
import { useActionState,useEffect,useState } from "react";
import { CalendarCog } from "lucide-react";
import { toast } from "sonner";
import { DateField } from "@/components/ui/date-field";
import { Picker } from "@/components/ui/picker";
import { saveTeachingImpact,type TeachingImpactActionState } from "@/features/calendar/server/actions";
import type { BellScheduleSummary } from "@/features/timetable/server/bell-calendar";
import type { TeachingImpactRow } from "@/features/calendar/server/teaching-impact";
const initialState:TeachingImpactActionState={};
const impactOptions=[{value:"NORMAL",label:"Normal",helper:"Normal teaching day"},{value:"NO_TEACHING",label:"No teaching",helper:"Closure or holiday"},{value:"PARTIAL_DAY",label:"Partial day",helper:"Teaching occurs for part of the day"},{value:"ALTERED_TIMETABLE",label:"Altered timetable",helper:"Different lesson timing/order"},{value:"EXAM_TIMETABLE",label:"Exam timetable",helper:"Exam-day operation"}];
export function TeachingImpactManager({schoolId,year,schedules,overrides}:{schoolId:string;year:number;schedules:BellScheduleSummary[];overrides:TeachingImpactRow[]}){
 const [state,action,pending]=useActionState(saveTeachingImpact,initialState);const [date,setDate]=useState(`${year}-01-01`);const [impact,setImpact]=useState("NORMAL");const [schedule,setSchedule]=useState("");
 useEffect(()=>{if(!state.message)return;if(state.success)toast.success(state.message);else toast.error(state.message)},[state]); const canSchedule=impact==="ALTERED_TIMETABLE"||impact==="EXAM_TIMETABLE"; const fieldClass="min-h-10 w-full rounded-[var(--radius-sm)] border border-border-subtle bg-surface-elevated px-3 text-sm outline-none transition hover:border-border focus:border-[color:var(--brand)]/50 focus:ring-4 focus:ring-[color:var(--brand-soft)]";
 return <section className="mt-5 rounded-[var(--radius-md)] bg-surface p-4 shadow-[var(--shadow-xs)] sm:p-5"><div className="flex items-start gap-2.5 border-b border-border-subtle pb-4"><span className="scolapro-tone-brand grid size-8 shrink-0 place-items-center rounded-[var(--radius-sm)]"><CalendarCog className="size-4"/></span><div><h2 className="scolapro-section-title">Teaching impact</h2><p className="scolapro-section-description !mt-0">Record how a specific calendar date affects teaching. Altered and exam days can select an effective bell schedule for that date.</p></div></div>
 <form action={action} className="mt-4 grid gap-3 md:grid-cols-2 md:items-end"><input type="hidden" name="schoolId" value={schoolId}/><DateField label="School date" name="date" value={date} onChange={setDate} required/><Picker label="Teaching impact" name="impact" value={impact} onChange={(value)=>{setImpact(value);if(value!=="ALTERED_TIMETABLE"&&value!=="EXAM_TIMETABLE")setSchedule("")}} placeholder="Choose teaching impact" options={impactOptions}/>{canSchedule?<Picker label="Bell schedule for this date" name="bellScheduleId" value={schedule} onChange={setSchedule} placeholder="Use automatically effective schedule" options={schedules.map(item=>({value:item.id,label:item.name,helper:`From ${item.effectiveFrom}`}))}/>:<input type="hidden" name="bellScheduleId" value=""/>}<div><label htmlFor="impact-reason" className="text-xs font-medium">Reason / note</label><input id="impact-reason" name="reason" className={`${fieldClass} mt-1.5`} placeholder="Optional calendar note"/></div><button type="submit" disabled={pending} className="scolapro-cta min-h-9 w-fit bg-brand px-3 text-xs font-semibold text-white disabled:opacity-50">{pending?"Saving…":"Save teaching impact"}</button></form>
 {overrides.length?<div className="mt-5 border-t border-border-subtle pt-4"><p className="text-xs font-semibold">Recent date overrides</p><div className="mt-2 divide-y divide-border-subtle">{overrides.slice(0,8).map(item=><div key={item.id} className="grid gap-1 py-2.5 sm:grid-cols-[7.5rem_10rem_1fr]"><span className="text-xs font-medium">{item.date}</span><span className="text-[0.68rem] font-semibold text-brand-strong">{item.impact.replaceAll("_"," ")}</span><span className="text-[0.68rem] text-muted-foreground">{item.bellScheduleName??item.reason??"—"}</span></div>)}</div></div>:null}</section>;
}
