"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export type RoomInventoryActionState={success?:boolean;message?:string};
const uuid=z.string().uuid();
export async function assignCustodian(_s:RoomInventoryActionState,fd:FormData):Promise<RoomInventoryActionState>{const p=z.object({roomId:uuid,staffId:uuid,effectiveFrom:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).safeParse({roomId:fd.get("roomId"),staffId:fd.get("staffId"),effectiveFrom:fd.get("effectiveFrom")});if(!p.success)return{message:"Choose a valid room, staff member and effective date."};const supabase=await createSupabaseServerClient();const{error}=await supabase.rpc("assign_room_inventory_custodian",{p_room_id:p.data.roomId,p_staff_member_id:p.data.staffId,p_effective_from:p.data.effectiveFrom});if(error)return{message:"Room responsibility could not be updated. Check your access and staff assignment."};revalidatePath("/school/room-inventory");return{success:true,message:"Room custodian updated."};}
export async function createItem(_s:RoomInventoryActionState,fd:FormData):Promise<RoomInventoryActionState>{const p=z.object({roomId:uuid,name:z.string().trim().min(1).max(160),ownership:z.enum(["government","school","personal"]),quantity:z.coerce.number().int().min(0).max(100000),condition:z.enum(["new","good","fair","poor","damaged","lost","disposed"]),assetNumber:z.string().trim().max(120).optional(),notes:z.string().trim().max(1000).optional()}).safeParse({roomId:fd.get("roomId"),name:fd.get("name"),ownership:fd.get("ownership"),quantity:fd.get("quantity"),condition:fd.get("condition"),assetNumber:fd.get("assetNumber")||undefined,notes:fd.get("notes")||undefined});if(!p.success)return{message:"Enter a valid item, ownership, quantity and condition."};const supabase=await createSupabaseServerClient();const{error}=await supabase.rpc("create_room_inventory_item",{p_room_id:p.data.roomId,p_item_name:p.data.name,p_ownership:p.data.ownership,p_quantity:p.data.quantity,p_condition:p.data.condition,p_asset_number:p.data.assetNumber||null,p_notes:p.data.notes||null});if(error)return{message:"Inventory item could not be added. Check your room assignment and values."};revalidatePath("/school/room-inventory");return{success:true,message:"Inventory item added."};}
export async function changeItem(_s:RoomInventoryActionState,fd:FormData):Promise<RoomInventoryActionState>{const p=z.object({itemId:uuid,eventType:z.enum(["received","quantity_increase","quantity_decrease","transferred_in","transferred_out","damaged","lost","disposed","correction","ownership_correction"]),delta:z.coerce.number().int().min(-100000).max(100000),condition:z.union([z.enum(["new","good","fair","poor","damaged","lost","disposed"]),z.literal("")]),ownership:z.union([z.enum(["government","school","personal"]),z.literal("")]),note:z.string().trim().max(1000).optional()}).safeParse({itemId:fd.get("itemId"),eventType:fd.get("eventType"),delta:fd.get("delta")||0,condition:fd.get("condition")||"",ownership:fd.get("ownership")||"",note:fd.get("note")||undefined});if(!p.success)return{message:"Enter a valid inventory change."};const supabase=await createSupabaseServerClient();const{error}=await supabase.rpc("change_room_inventory_item",{p_item_id:p.data.itemId,p_event_type:p.data.eventType,p_quantity_delta:p.data.delta,p_condition:p.data.condition||null,p_ownership:p.data.ownership||null,p_note:p.data.note||null});if(error)return{message:"Inventory change could not be recorded. Check quantity and your room access."};revalidatePath("/school/room-inventory");return{success:true,message:"Inventory change recorded."};}
export async function verifyInventory(_s:RoomInventoryActionState,fd:FormData):Promise<RoomInventoryActionState>{const p=z.object({roomId:uuid,status:z.enum(["confirmed","exceptions_noted"]),notes:z.string().trim().max(1000).optional()}).safeParse({roomId:fd.get("roomId"),status:fd.get("status"),notes:fd.get("notes")||undefined});if(!p.success)return{message:"Choose a valid room and verification status."};const supabase=await createSupabaseServerClient();const{error}=await supabase.rpc("verify_room_inventory",{p_room_id:p.data.roomId,p_status:p.data.status,p_notes:p.data.notes||null});if(error)return{message:"Inventory could not be verified. Check your room access and try again."};revalidatePath("/school/room-inventory");return{success:true,message:p.data.status==="confirmed"?"Inventory confirmed with no changes.":"Inventory verified with exceptions noted."};}
